import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { Header } from "@/components/header";
import {Providers} from "@/provider"
import "./globals.css";
import '@rainbow-me/rainbowkit/styles.css';
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "RDO Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={`${inter.className} !bg-[#FFFFFF] text-white min-h-screen flex flex-col relative`} >
        <Providers>
          <Header />
          <main className="flex-grow">
            {children}
          </main>
        </Providers>

        </body>
    </html>
  );
}
